-- Generated by scripts/audit-resource-dates.mjs
-- Run: date 2026-04-23T14:31:04.386Z
-- Review each statement before applying. Comments show detection source + delta.

-- ai  delta=60d  source=og:article:published_time  title="OpenClaw creator Peter Steinberger joins OpenAI"
UPDATE resources SET date = '2026-02-15' WHERE id = 'efcc5f83-807d-4527-af4c-8d7c66d1e509';
-- ai  delta=493d  source=og:article:published_time  title="The 2025 API Evangelist Vision"
UPDATE resources SET date = '2024-12-09' WHERE id = 'bf6fa3c3-8195-4e86-ae61-99dfb11aa6c1';
-- ai  delta=15d  source=og:article:published_time  title="Cris Valenzuela, Runway CEO: A Fortt Knox Update"
UPDATE resources SET date = '2026-04-01' WHERE id = '2cdc6dda-55f2-471d-aaa8-067fec355ec1';
-- ai  delta=183d  source=itemprop:datePublished  title="Ryne Saxe: Powering Cross-Chain Stablecoin Liquidity with Eco | Off-Chain Podcast"
UPDATE resources SET date = '2025-10-15' WHERE id = '9c270ce5-9b4b-4e44-941a-a2bd7c520235';
-- ai  delta=-16d  source=og:article:published_time  title="Onchain AI Identity: What ERC-8004 Unlocks for Agent Infrastructure"
UPDATE resources SET date = '2026-02-17' WHERE id = 'c084391f-d5b4-4195-8bca-b4749cf8609d';
-- ai  delta=-16d  source=itemprop:datePublished  title="ERC-8004 + x402 AI Agent Registry Explained"
UPDATE resources SET date = '2026-02-05' WHERE id = '4db47c96-2b94-4501-bffb-831a760ff6df';
-- ai  delta=146d  source=og:article:published_time  title="The Story Behind ERC-8004 & Next Steps"
UPDATE resources SET date = '2025-08-22' WHERE id = '7427b130-87e9-40c9-80fb-0a35229ffbea';
-- brands  delta=408d  source=json-ld:datePublished  title="Reddit cofounder Alexis Ohanian wants to buy TikTok—and add a bold new crypto element"
UPDATE resources SET date = '2025-03-04' WHERE id = '40d23a99-ae73-4133-ba15-ca39896c7ff2';
-- brands  delta=-14d  source=itemprop:datePublished  title="ADFW 2025: Yoni Assia, Co-Founder & CEO, eToro"
UPDATE resources SET date = '2025-12-15' WHERE id = 'd35cafe2-ae67-4ae1-b668-26f3ea56b636';
-- brands  delta=-77d  source=og:article:published_time  title="NFT Marketing Trends to Watch in 2025: AI, Consumer Behavior"
UPDATE resources SET date = '2025-03-19' WHERE id = '5f5ed679-3fa5-4947-bd59-e8b4bb6538f6';
-- brands  delta=-131d  source=og:article:published_time  title="Best Web3 Loyalty Programs for eCommerce (2025)"
UPDATE resources SET date = '2025-05-12' WHERE id = 'f802ec34-af63-4d9f-a966-937111da0459';
-- creator  delta=133d  source=og:article:published_time  title="This Artist's 'Self Checkout' Lets You Pay What You Wish at Art Basel Miami Beach"
UPDATE resources SET date = '2025-12-04' WHERE id = 'b5a0ecc6-4945-4717-9615-0176f7fac6f8';
-- creator  delta=1298d  source=time[datetime]  title="Music NFTs & The Next Generation Of Music | Cooper Turley"
UPDATE resources SET date = '2022-09-26' WHERE id = '2d9d0c91-0179-4a68-8ea5-a851ab83a045';
-- creator  delta=52d  source=json-ld:datePublished  title="Sweet CEO on transforming sports NFTs from static collectables to programmable IP"
UPDATE resources SET date = '2026-02-17' WHERE id = '87633236-6e7d-47a5-963f-8c533d9de65f';
-- creator  delta=440d  source=itemprop:datePublished  title="The modular blockchain thesis with Andy from The Rollup"
UPDATE resources SET date = '2024-02-16' WHERE id = '7cd63a94-8dc7-4e71-98b6-b966ceaf8ec5';
-- creator  delta=-360d  source=json-ld:datePublished  title="From Adoption to Annexation (Meltem Demirors)"
UPDATE resources SET date = '2026-02-24' WHERE id = '0e269ea5-24c8-4e9a-a29b-7fabf255b12e';
-- creator  delta=-79d  source=json-ld:datePublished  title="Bitcoin to hit all-time high in 2025, predicts Anthony Pompliano"
UPDATE resources SET date = '2025-04-04' WHERE id = '0441ff8b-e3d3-4590-acbe-e78e3e3aebe8';
-- creator  delta=952d  source=og:article:published_time  title="YAPLive: NFT Basics and Beyond with John Kraski et al"
UPDATE resources SET date = '2022-03-25' WHERE id = 'e14cacb6-d329-4292-a04d-f388f9e9c98d';
-- creator  delta=-106d  source=og:article:published_time  title="The Comprehensive Guide to NFT Royalties"
UPDATE resources SET date = '2024-04-16' WHERE id = '7c96f314-d4dc-46c2-8262-f8385c1372da';
-- culture  delta=785d  source=og:article:published_time  title="Greg Solano Resumes CEO Role At Yuga Labs"
UPDATE resources SET date = '2024-02-21' WHERE id = '3f5bfe58-b46e-4cab-81d1-ac32f9588a3b';
-- culture  delta=615d  source=og:article:published_time  title="VeeCon Gathering in LA Highlights Serial Entrepreneur's World"
UPDATE resources SET date = '2024-08-09' WHERE id = '34dc477e-0401-4690-863f-e4d17bf88681';
-- culture  delta=802d  source=og:article:published_time  title="Pindar Van Arman X NFT Paris: Reflection – A Milestone in AI and Generative Art"
UPDATE resources SET date = '2024-02-04' WHERE id = 'f67da6a8-738a-4dee-bff8-7c5b73750169';
-- culture  delta=370d  source=og:article:published_time  title="Is a Crypto-Friendly Administration Igniting New Passion for NFTs?"
UPDATE resources SET date = '2025-03-28' WHERE id = 'b0a77a0c-5331-4568-9e3d-ef0ff42a94d1';
-- culture  delta=980d  source=json-ld:datePublished  title="Generative Art Summer"
UPDATE resources SET date = '2023-07-27' WHERE id = '2342927e-aa76-4a14-ba8e-31386c9b60ce';
-- culture  delta=-21d  source=json-ld:datePublished  title="Bryan Brinkman — live from Marfa, in conversation"
UPDATE resources SET date = '2025-12-30' WHERE id = 'fbf394b5-43c7-4ed1-b57a-11d44c8ba213';
-- culture  delta=-24d  source=itemprop:datePublished  title="Kevin Abosch x TAEX — Paris Photo 2025"
UPDATE resources SET date = '2025-12-04' WHERE id = 'db19c4cb-42bc-4b4e-9d10-66d2dacde5b3';
-- culture  delta=-53d  source=og:article:published_time  title="Meet the artist: Grant Yun makes digital paintings"
UPDATE resources SET date = '2025-06-23' WHERE id = '7018dd50-9c4f-4de3-95e3-c09d40db4a18';
-- culture  delta=-50d  source=og:article:published_time  title="Justin Aversano — The Most Promising NFT Photography Projects 2025"
UPDATE resources SET date = '2025-05-28' WHERE id = '0c9cc373-e0a5-42dc-a500-71221b487e7f';
-- culture  delta=-333d  source=og:article:published_time  title="DAO Models to Watch in 2025: From Protocol DAOs to Community DAOs"
UPDATE resources SET date = '2025-11-30' WHERE id = '79d7830d-350d-49d6-bc27-6d331755e330';
-- culture  delta=-191d  source=og:article:published_time  title="Digital Art Isn't Dead — But It Is at a Crossroads"
UPDATE resources SET date = '2025-04-10' WHERE id = 'bdc0d7d1-9434-4109-8285-5fe6b5cfd397';
-- culture  delta=378d  source=itemprop:datePublished  title="NODE TO NODE — Art Salon Paris (Kate Vass Galerie)"
UPDATE resources SET date = '2023-09-19' WHERE id = '9dbbb83b-bcda-4a80-b1b4-2b1767149572';
-- culture  delta=-524d  source=json-ld:datePublished  title="Live From Marfa: In Conversation with Natalie Stone"
UPDATE resources SET date = '2026-01-21' WHERE id = 'd768214f-3832-4db8-b7bc-fcbda8424d2b';
-- culture  delta=58d  source=og:article:published_time  title="Bright Moments founder Seth Goldstein in conversation with Fakewhale"
UPDATE resources SET date = '2024-04-04' WHERE id = '010e02e4-986f-4059-8e4b-e348582c0283';
-- culture  delta=-258d  source=itemprop:datePublished  title="Michael Bouhanna (Sotheby's) on the evolution of digital art"
UPDATE resources SET date = '2024-11-14' WHERE id = '99777f64-5e5f-4e46-b58d-aca292d7d49a';
-- culture  delta=-262d  source=json-ld:datePublished  title="DAO-Enabled NFT Platforms: Ultimate Guide"
UPDATE resources SET date = '2024-09-19' WHERE id = '780d88c4-20f1-4ce2-bcad-711e45ac7cb7';
-- culture  delta=-128d  source=json-ld:datePublished  title="Interview with AI artist and poet Sasha Stiles"
UPDATE resources SET date = '2023-09-06' WHERE id = '481dc2ba-b07b-4d8a-9742-4cf6514c7a91';
-- defi  delta=288d  source=itemprop:datePublished  title="RWA Tokenization in 2025: From Niche to Necessity | Bhaji Illuminati, CEO of Centrifuge"
UPDATE resources SET date = '2025-06-26' WHERE id = 'cea0b422-aa18-4a10-aa5c-318955d76f81';
-- defi  delta=207d  source=og:article:published_time  title="3 questions for… | Stéphanie Cabossioras, SG Forge “What do we need to know about stablecoins in 2025?”"
UPDATE resources SET date = '2025-05-12' WHERE id = '839b5910-a75c-4cc0-9c70-85e8c3a4cd0c';
-- defi  delta=-239d  source=itemprop:datePublished  title="The Safest Dollar on the Internet | Circle CEO Jeremy Allaire"
UPDATE resources SET date = '2026-01-26' WHERE id = 'fe347166-769b-44af-b8d1-2fb324d7f12a';
-- defi  delta=36d  source=itemprop:datePublished  title="Kain Warwick: Why Crypto Is BROKEN in 2025"
UPDATE resources SET date = '2025-01-24' WHERE id = 'c894bf0c-90d0-4509-8c9c-83c669282d05';
-- defi  delta=-451d  source=json-ld:datePublished  title="State of DeFi 2025"
UPDATE resources SET date = '2026-03-28' WHERE id = 'dc7ac1ec-6e52-48d8-8ff0-5a227ce8d228';
-- defi  delta=-294d  source=json-ld:@graph.datePublished  title="NFT-Backed Loans Market: Global Analysis Report 2025-2035"
UPDATE resources SET date = '2025-10-22' WHERE id = 'ece787c5-e047-4311-9211-1627c91439c7';
-- domains  delta=306d  source=og:article:published_time  title="Money, Ownership And Identity With Nick Johnson Of ENS"
UPDATE resources SET date = '2024-09-21' WHERE id = '9f00a209-3217-45e2-9f71-757a3dbec723';
-- domains  delta=-294d  source=itemprop:datePublished  title="Sandy Carter — Beyond the Myths: Building Your AI-First Future"
UPDATE resources SET date = '2026-01-20' WHERE id = '02751f4b-4622-46a2-8cd5-a2f00fca0447';
-- gaming  delta=35d  source=og:article:published_time  title="The Unraveling and Rebirth of Digital Ownership: A Post-Mortem on the 2021 NFT Empire and the Rise of Verifiable Utility"
UPDATE resources SET date = '2025-11-05' WHERE id = '3527173f-9183-4d6a-a0c5-66c73ef7c854';
-- gaming  delta=401d  source=og:article:published_time  title="NFTs and Gaming: Redefining Digital Ownership for Player"
UPDATE resources SET date = '2024-09-09' WHERE id = '80cd1a08-2cc3-426f-9976-f02fc16a9a0d';
-- gaming  delta=-140d  source=og:article:published_time  title="Why NFT Gaming Economies Struggle and What Works Instead"
UPDATE resources SET date = '2026-01-23' WHERE id = 'c5a6ecc3-1999-4f7c-a090-2ab4dae78447';
-- gaming  delta=137d  source=og:article:published_time  title="Sebastien Borget on how The Sandbox's vision has evolved"
UPDATE resources SET date = '2025-01-15' WHERE id = 'abe9d6a6-16b8-42e4-92fb-082f4d7fe028';
-- gaming  delta=-313d  source=json-ld:datePublished  title="A-Rod Corp: what Alex Rodriguez's investments teach about reinvention"
UPDATE resources SET date = '2026-04-10' WHERE id = '34164726-9e20-4ec6-994f-1897a6b819cc';
-- gaming  delta=-27d  source=itemprop:datePublished  title="Robby Yung (Animoca Brands) at Web Summit Qatar 2025"
UPDATE resources SET date = '2025-02-28' WHERE id = '5904e5cf-e91b-4a3b-8ace-c067ca15fec6';
-- gaming  delta=-268d  source=json-ld:datePublished  title="State of Blockchain Gaming in 2025"
UPDATE resources SET date = '2025-09-26' WHERE id = '4c0794e6-eae9-4e26-8cd1-25364f62cccf';
-- gaming  delta=-245d  source=json-ld:datePublished  title="Gaming NFT Market Size & Growth Forecasts 2025-2034"
UPDATE resources SET date = '2025-02-01' WHERE id = '85700a16-3c6e-432b-b8e5-745ae22dd4ef';
-- infra  delta=169d  source=og:article:published_time  title="Solana co-founder Anatoly Yakovenko is a big fan of agentic coding"
UPDATE resources SET date = '2025-10-29' WHERE id = 'cacc08f6-42c8-44fd-b6d3-662d2716b5a2';
-- infra  delta=-37d  source=itemprop:datePublished  title="What's Next for Ethereum: Consensys & Chainlink at SmartCon"
UPDATE resources SET date = '2025-11-07' WHERE id = 'cc1f39be-550d-4246-be65-f03638492d1f';
-- infra  delta=-245d  source=json-ld:datePublished  title="Marc Boiron (Polygon Labs) — Payments will define Web3"
UPDATE resources SET date = '2026-04-03' WHERE id = '65d1a21e-f440-439c-994e-b87886da7ce8';
-- infra  delta=-142d  source=og:article:published_time  title="Eli Ben-Sasson: enterprise blockchains will fail if they don't embrace decentralization"
UPDATE resources SET date = '2025-10-21' WHERE id = '262a9932-0555-440d-8ff4-fe8d4d57ce39';
-- infra  delta=-27d  source=og:article:published_time  title="Adam Back presents Blockstream's Bitcoin-first infrastructure vision"
UPDATE resources SET date = '2025-05-28' WHERE id = '336565e7-6868-4e03-8e1e-a997e6139141';
-- infra  delta=-20d  source=itemprop:datePublished  title="Charles Hoskinson keynote at Paris Blockchain Week 2025"
UPDATE resources SET date = '2025-04-30' WHERE id = '74f29830-036b-4e93-b99c-c26269d2d04d';
-- infra  delta=-23d  source=og:article:published_time  title="Chainlink in 2025: The Final Stage of Blockchain Adoption"
UPDATE resources SET date = '2025-01-24' WHERE id = '4b4c508a-eeda-4056-b9e0-22fce03d6501';
-- infra  delta=-650d  source=og:article:published_time  title="Revenge of the Atoms (Pascal Gauthier)"
UPDATE resources SET date = '2026-03-13' WHERE id = 'deb1bf3b-b412-4a19-a658-5cc41614a00d';
-- marketplaces  delta=624d  source=og:article:published_time  title="Songadaymann sues SEC after using NFTs to sell songs he writes every day"
UPDATE resources SET date = '2024-07-31' WHERE id = 'abe4ff5f-7783-4f36-9c3e-de1bbde15116';
-- marketplaces  delta=181d  source=json-ld:datePublished  title="OpenSea CEO Devin Finzer Confirms SEA Token Launch, 'Trade Everything' Strategy"
UPDATE resources SET date = '2025-10-17' WHERE id = 'aa9d59a8-d09c-49e9-8352-8988e78d8d0a';
-- marketplaces  delta=-21d  source=og:article:published_time  title="SEC Ends NFT Crackdowns in 2025: Collectibles vs. Securities"
UPDATE resources SET date = '2025-12-22' WHERE id = 'ce12c0f2-c53c-43c9-8dd3-fa8b2729675f';
-- marketplaces  delta=-32d  source=json-ld:datePublished  title="What crypto exchanges are watching in 2026, per OKX's Haider Rafique"
UPDATE resources SET date = '2026-01-02' WHERE id = '3e10953b-4f0c-4b0e-b8e6-9f036d9ccf5c';
-- marketplaces  delta=-164d  source=og:article:published_time  title="Top NFT Marketplace Development Companies"
UPDATE resources SET date = '2026-04-02' WHERE id = 'cb30bc36-3013-4e70-938a-11d7c90e917c';
-- marketplaces  delta=-167d  source=og:article:published_time  title="Messari CEO Eric Turner on restructuring and new direction"
UPDATE resources SET date = '2026-03-17' WHERE id = '2248a470-571c-411b-bbaf-bb2c9ab24a72';
-- marketplaces  delta=-65d  source=json-ld:@graph.datePublished  title="OpenSea Investment Analysis 2025: OS2 Platform, SEA Token"
UPDATE resources SET date = '2025-10-05' WHERE id = '362ebd01-de25-4722-90ee-73ff4e1c4a89';
-- marketplaces  delta=324d  source=json-ld:datePublished  title="Messari's New CEO Eric Turner Doesn't Want to Talk Politics"
UPDATE resources SET date = '2024-07-26' WHERE id = 'c43e768a-87b3-4eef-8fca-8deb897630be';
-- marketplaces  delta=-360d  source=json-ld:datePublished  title="Ripple CEO warns against weaponization of crypto policy"
UPDATE resources SET date = '2026-03-27' WHERE id = '892053a9-e1c2-4a1f-84b4-6580ed4d0042';
-- marketplaces  delta=-126d  source=json-ld:@graph.datePublished  title="Top 10 NFT Marketplaces by Trading Volume in 2025"
UPDATE resources SET date = '2025-08-05' WHERE id = '961c627e-94ba-4de0-b72a-8dfdf199be5d';
-- marketplaces  delta=-322d  source=itemprop:datePublished  title="John Crain & Jonathan Perkins — SuperRare Labs"
UPDATE resources SET date = '2024-03-18' WHERE id = 'd6f5367e-5ca7-45dc-be46-d433b41b28ad';
-- rwa  delta=42d  source=og:article:published_time  title="Securitize CEO Carlos Domingo on tokenized shares and SPAC merger"
UPDATE resources SET date = '2026-03-05' WHERE id = '53cc0138-3805-47ee-9feb-040d09dba4a1';
-- rwa  delta=36d  source=og:article:published_time  title="Arab Bank Switzerland Middle East receives in-principle ADGM advisory licence"
UPDATE resources SET date = '2025-12-10' WHERE id = '078eeb0a-f1e6-4240-9509-08155489ca40';
-- rwa  delta=-102d  source=itemprop:datePublished  title="Breakpoint Keynote: Figure (Mike Cagney)"
UPDATE resources SET date = '2025-12-12' WHERE id = 'c76a37ee-08dd-4063-95f6-31b814f12c8d';
-- social  delta=260d  source=itemprop:datePublished  title="Pudgy Penguins CEO Luca Netz on the NFT Resurgence Everyone Is Missing"
UPDATE resources SET date = '2025-07-24' WHERE id = '43b7728f-867e-4f6b-b32e-c823770eb0e9';